.\" Manpage for jvmutil.
.TH man 1 "23 September 2022" "0.1.9-alpha.9" "jvmutil manpage"
.SH NAME
jvmutil \- view and manage the currently installed and active JVMs
.SH SYNOPSIS
jvmutil [-h] [-q] [-y] {list,active,find,switch,relink} ...
.SH DESCRIPTION

.SH OPTIONS
.SS options:
  -h, --help            show this help message and exit
  -q, --quiet           Reduce informational messages
  -y, --force-first     Always choose the first option

.SS subcommands:
  The action to perform

  {list,active,find,switch}
    list                List the available JVMS
    active              Get the currently selected JVM
    find                Get info about an installed JVM
    switch              Change the active JVM
    relink              Setup the symlink which controls JVM finding

.SS subcommand detail:
.TP
list \- List the active JVMs
jvmutil list [-h] [-f FILTER] [--fields FIELDS] [--display {table,json,raw}]

options:
  -h, --help            show this help message and exit
  -f FILTER, --filter FILTER
                        Filter the output by a specified tag query
  --fields FIELDS       Comma-separated list of fields to display
  --display {table,json,raw}
                        Select the display mode

.TP
active \- Get the currently selected JVM
jvmutil active [-h] [--fields FIELDS] [--display {table,json,raw}]

options:
  -h, --help            show this help message and exit
  --fields FIELDS       Comma-separated list of fields to display
  --display {table,json,raw}
                        Select the display mode

.TP
find \- Get info about an installed JVM
jvmutil find [-h] [--fields FIELDS] [--display {table,json,raw}] target

positional arguments:
  target                The JVM to look for

options:
  -h, --help            show this help message and exit
  --fields FIELDS       Comma-separated list of fields to display
  --display {table,json,raw}
                        Select the display mode

.TP
switch \- Change the active JVM
jvmutil switch [-h] [-l] target

positional arguments:
  target       The JVM to look for

options:
  -h, --help            show this help message and exit

.SH FILTERS
The `switch` and `find` commands both have a "filter" as their primary
argument, and the `list` command accepts a filter passed to the `-f` flag.
Filters operate over the 'tag' field of a JVM, and have one of the following
formats:
.IP \[bu]
`VERSION`: A semantic version number or subpart thereof, like `1.8` or `11`.
  Matches all JDKs with a version starting with the one provided.
.IP \[bu]
`NAME`: Any other non-version text. Matches some part of the name of the
  JDK, like `corretto` or `openjdk`.
.IP \[bu]
`NAME:VERSION`: Match both the name and the version. e.g. `corretto:11`.
.IP \[bu]
`NAME:VERSION:ARCH`: Match the name, version, and platform architecture. e.g.
  `corretto:11:arm64`. Note that either `NAME` or `VERSION` can be blank to
  represent "Any name" or "Any version", e.g. `:1.8:arm64`.

.SH OUTPUT FORMAT
The `find`, `list`, and `active` commands all output tables with several
points of data for every JDK they find by default. The standard set of fields is
`tag,name,version,arch,provider,path`. By providing a comma-separated list
of field names to the `--fields` flag you can limit or re-order this output.
Additionally, the `--display` flag can accept one of `table` (the default),
`json`, or `raw` to change the format of the output.

.SH AUTHOR
Jake Trimble (https://github.com/jtrim777-dev/)
