name: Get Info
on:
  pull_request:
    types: [synchronize]

jobs:
  get_tag_info:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Previous Tag
        id: get_tags
        run: |
          git fetch -a
          echo "Raw:"
          echo -e $(git tag --sort "-committerdate")
          echo -e $(git tag --sort "-committerdate" | sed '/-/d')
          echo -e $(git tag --sort "-committerdate" | sed '/-/d' | sed -n 1p)
          echo ::set-output name=current_tag::$(git tag --sort "-committerdate" | sed '/-/d' | sed -n 1p)
      - name: Check Output
        run: echo "${{ steps.get_tags.current_tag }}"